### ISSUE TITLE
Defaults values for non-verbose version

### ISSUE THREAD

**Issue by pythouille** [johentsch/specs#2]
For each key in the schema, we can define default values so that only 'important' keys are needed. (This is different to 'compressed' version which also erase entire unnecessary measure). Besides, could some of these default values be part of the schema?

Current proposition:
- `count` : `<previous 'count'> + 1`, and to 1 for the first measure (cannot be overridden)
- `id` : defaults to current 'count' (converted to str)
- `number` : defaults to  `<previous 'number'> + 1`, and to 1 for the first measure
- `name` : defaults to current `number` (converted to string) ; if previous `name` is in the form of a number followed by a single letter (e.g. "19a"), the same letter is added on current name ("20a") (edit: see https://github.com/johentsch/specs/issues/3#issuecomment-1730837327)
- `time_signature` : defaults to the previous `time_signature`, and to `null` for the first measure
- `nominal_length` : defaults to `4.0 * numerator/denominator` based on current time signature
- `actual_length` : defaults to current `nominal_length`
- `qstamp` : defaults to `<previous 'qstamp'> + <previous 'actual_duration'`, and 0.0 for the first measure
- `start_repeat` : defaults to False
- `end_repeat` : defaults to False
- `next` : defaults to `[<current 'count'> + 1]`, and to `[-1]` for the last measure

A verbose version can be easily built by iterating on each measure to add default values for missing keys -- in the order above ; using both previous and current measure's info.

Any changes to consider before integrating this as official specs?

**Comment by magiraud** [comment]
There is also `number`, which also defaults to current `count`.

> `count` : defaults to <previous 'count'> + 1, and to 1 for the first measure

I understand that it's here the only possible value, it cannot be overriden to something else.

**Comment by pythouille** [comment]
I added `number`, which defaults to `<previous number> + 1` (instead of `count`), as measures with `count` 10, 11, 12 may be with `number` 9, 10, 11 etc. (in the case of anacruses, split measures or any offset).

**Comment by johentsch** [comment]
> Any changes to consider before integrating this as official specs?

Thank you @pythouille and @magiraud. I've spent some time thinking about the role of these defaults and where/how it makes sense to integrate them into the specs. As I view it, these defaults are backbone of our compression algorithm and, therefore, are important for the user wanting to write down a compressed measure map. 

I would like us to merge this discussion with #3, turning it into the exact set of conditions that needs to be fulfilled in order to omit an entry. The question of "non-/verbose" (which, so far, has touched touched only on start/end repeat), I think, is a small implementation detail that will probably be based on a boolean parameter to those methods that output JSON.

**Comment by johentsch** [comment]
UPDATE: Merging this discussion into #3 through the [latest comment there](https://github.com/johentsch/specs/issues/3#issuecomment-1733509899) and the referenced implementation.

Limiting the "non-verbose" idea to `start_repeat` and `end_repeat` for which I just added the default value False (c59e505).
